# Datasource mariadb 설정
spring:
  output:
    ansi:
      enabled: always
  #  datasource:
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://localhost:3306/Mapzip
  #    username: root
  #    password: 1234

  #H2 console

  # Datasource H2 설정
  #spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: sa
    password:

  jpa:
    hibernate:
      #      ddl-auto: update #update the schema with the given values.
      ddl-auto: create
    #SQL문으로 출력하기
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect #OK
        format_sql: true #To beautify or pretty print the SQL
        show-sql: true #show sql

  profiles:
    include: secret # secret.yml 추가

  # swagger 에러 해결
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#show parameter binding
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: DEBUG
        SQL: DEBUG

